name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x # 或者使用你项目需要的Node.js版本
      - name: Enable Corepack
        run: corepack enable
      - name: Use pnpm
        run: corepack prepare pnpm@8.6.2 --activate
      - name: Install package
        run: pnpm install
      - name: Testing
        run: pnpm test
